version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: emergence-backend
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    depends_on:
      - litellm

  litellm:
    image: litellm/litellm:latest
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LITELLM_PROXY_LOG: "true"
      LITELLM_BUDGETS: "true"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: --config /app/config.yaml --port 4000
