# Cloud Run Service Configuration - Stable Deployment
# 100% traffic to new revision after successful canary validation
# Projet: emergence-469005

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emergence-app
  namespace: 'emergence-469005'
  labels:
    cloud.googleapis.com/location: europe-west1
    app: emergence
    stage: stable
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: firestore-sync@emergence-469005.iam.gserviceaccount.com
      containers:
      - name: emergence-app
        image: gcr.io/emergence-469005/emergence-app:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: emergence-469005
        - name: AUTH_DEV_MODE
          value: '0'
        - name: SESSION_INACTIVITY_TIMEOUT_MINUTES
          value: '30'
        - name: SESSION_CLEANUP_INTERVAL_SECONDS
          value: '60'
        - name: SESSION_WARNING_BEFORE_TIMEOUT_SECONDS
          value: '120'
        - name: CONCEPT_RECALL_METRICS_ENABLED
          value: '1'
        # Email Configuration for Password Reset
        - name: EMAIL_ENABLED
          value: '1'
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: '587'
        - name: SMTP_USER
          value: emergence.app.ch@gmail.com
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SMTP_PASSWORD
              key: latest
        - name: SMTP_FROM_EMAIL
          value: emergence.app.ch@gmail.com
        - name: SMTP_FROM_NAME
          value: ÉMERGENCE
        - name: SMTP_USE_TLS
          value: '1'
        # API Keys
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: latest
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: GEMINI_API_KEY
              key: latest
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: GEMINI_API_KEY
              key: latest
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ANTHROPIC_API_KEY
              key: latest
        # OAuth Configuration
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: GOOGLE_OAUTH_CLIENT_ID
              key: latest
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: GOOGLE_OAUTH_CLIENT_SECRET
              key: latest
        - name: GOOGLE_ALLOWED_EMAILS
          value: gonzalefernando@gmail.com
        - name: GOOGLE_ALLOWLIST_MODE
          value: email
        - name: AUTH_ADMIN_EMAILS
          value: gonzalefernando@gmail.com
        - name: AUTH_DEV_DEFAULT_EMAIL
          value: gonzalefernando@gmail.com
        - name: AUTH_ALLOWLIST_SNAPSHOT_BACKEND
          value: firestore
        - name: AUTH_ALLOWLIST_SNAPSHOT_COLLECTION
          value: auth_config
        - name: AUTH_ALLOWLIST_SNAPSHOT_DOCUMENT
          value: allowlist
        - name: AUTH_ALLOWLIST_SNAPSHOT_PROJECT
          value: emergence-469005
        # AUTH_ALLOWLIST_SEED removed - only used for local DB seeding, not needed in production
        # AI Agent Models
        - name: ANIMA_PROVIDER
          value: openai
        - name: ANIMA_MODEL
          value: gpt-4o-mini
        - name: NEO_PROVIDER
          value: google
        - name: NEO_MODEL
          value: models/gemini-1.5-flash-latest
        - name: NEXUS_PROVIDER
          value: anthropic
        - name: NEXUS_MODEL
          value: claude-3-haiku
        # ElevenLabs Voice Configuration
        - name: ELEVENLABS_API_KEY
          value: sk_691ec9b632497fc6954732fbfa1e4f33a54ba834c4e3c008
        - name: ELEVENLABS_VOICE_ID
          value: ohItIVrXTBI80RrUECOD
        - name: ELEVENLABS_MODEL_ID
          value: eleven_multilingual_v2
        # Telemetry & Cache
        - name: ANONYMIZED_TELEMETRY
          value: 'False'
        - name: CHROMA_DISABLE_TELEMETRY
          value: '1'
        - name: RAG_CACHE_REDIS_URL
          value: redis://localhost:6379/0
        - name: RAG_CACHE_TTL_SECONDS
          value: '300'
        - name: RAG_CACHE_MAX_MEMORY_ITEMS
          value: '500'
        - name: RAG_CACHE_ENABLED
          value: 'true'
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30

  traffic:
  # New revision (promoted from canary) receives 100% traffic
  - percent: 100
    latestRevision: true
    tag: stable
