# Cloud Run Service Configuration - Stable Deployment
# 100% traffic to new revision after successful canary validation
# Projet: emergence-469005

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emergence-app
  namespace: 'emergence-469005'
  labels:
    cloud.googleapis.com/location: europe-west1
    app: emergence
    stage: stable
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: emergence-469005@appspot.gserviceaccount.com
      containers:
      - name: emergence-app
        image: app  # Replaced by Skaffold/Cloud Deploy
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        - name: GOOGLE_CLOUD_PROJECT
          value: emergence-469005
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-credentials.json
        - name: AUTH_DEV_MODE
          value: '0'
        - name: SESSION_INACTIVITY_TIMEOUT_MINUTES
          value: '30'
        - name: SESSION_CLEANUP_INTERVAL_SECONDS
          value: '60'
        - name: SESSION_WARNING_BEFORE_TIMEOUT_SECONDS
          value: '120'
        - name: CONCEPT_RECALL_METRICS_ENABLED
          value: '1'
        # Email Configuration for Password Reset
        - name: EMAIL_ENABLED
          value: '1'
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: '587'
        - name: SMTP_USER
          value: gonzalefernando@gmail.com
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SMTP_PASSWORD
              key: latest
        - name: SMTP_FROM_EMAIL
          value: gonzalefernando@gmail.com
        - name: SMTP_FROM_NAME
          value: ÉMERGENCE
        - name: SMTP_USE_TLS
          value: '1'
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: gcp-credentials

  traffic:
  # New revision (promoted from canary) receives 100% traffic
  - percent: 100
    latestRevision: true
    tag: stable
