apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emergence-app
  namespace: "486095406755"
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "20"
        run.googleapis.com/launch-stage: GA
    spec:
      containerConcurrency: 80
      containers:
        - image: europe-west1-docker.pkg.dev/emergence-469005/app/emergence-app@sha256:040bc42c1d2ed1959c72d4c47c8d27107668dc387afa3075ee84ac0822abe1e0
          command: ["python"]
          args: ["-m","uvicorn","backend.main:app","--host","0.0.0.0","--port","8080"]
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef: { name: OPENAI_API_KEY, key: "5" }
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef: { name: GOOGLE_API_KEY, key: "5" }
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef: { name: ANTHROPIC_API_KEY, key: "5" }
            - name: PYTHONPATH
              value: /app/src
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits: { cpu: "1000m", memory: 512Mi }
          startupProbe:
            tcpSocket: { port: 8080 }
            periodSeconds: 240
            timeoutSeconds: 240
            failureThreshold: 1
      serviceAccountName: 486095406755-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - percent: 100
      # garde la révision stable actuelle si nécessaire; sinon laisse Cloud Run router vers latestReady
    - tag: canary
      latestRevision: true
