apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emergence-auth-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west1
    app: emergence
    service: auth
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/cpu-throttling: 'false'
      labels:
        app: emergence
        service: auth
        version: v1
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 486095406755-compute@developer.gserviceaccount.com
      containers:
      - name: auth-service
        image: europe-west1-docker.pkg.dev/emergence-469005/app/emergence-auth-service:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # JWT Configuration
        - name: AUTH_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: AUTH_JWT_SECRET
              key: latest
        - name: AUTH_JWT_ISSUER
          value: "emergence.app"
        - name: AUTH_JWT_AUDIENCE
          value: "emergence-app"
        - name: AUTH_JWT_TTL_DAYS
          value: "7"
        - name: AUTH_JWT_ALGORITHM
          value: "HS256"

        # Admin Configuration
        - name: AUTH_ADMIN_EMAILS
          valueFrom:
            secretKeyRef:
              name: AUTH_ADMIN_EMAILS
              key: latest

        # Database Configuration
        - name: EMERGENCE_DB_PATH
          value: "/app/data/emergence.db"

        # SMTP Configuration for password reset
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: SMTP_HOST
              key: latest
              optional: true
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: SMTP_USERNAME
              key: latest
              optional: true
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SMTP_PASSWORD
              key: latest
              optional: true
        - name: SMTP_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: SMTP_FROM_EMAIL
              key: latest
              optional: true
        - name: SMTP_FROM_NAME
          value: "Emergence"

        # Service Configuration
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SERVICE_NAME
          value: "auth-service"

        resources:
          limits:
            cpu: '2'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 512Mi

        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

  traffic:
  - latestRevision: true
    percent: 100
