apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emergence-app
spec:
  template:
    spec:
      serviceAccountName: 486095406755-compute@developer.gserviceaccount.com
      containers:
        - image: europe-west1-docker.pkg.dev/emergence-469005/app/emergence-app@sha256:6b91f6a419b85b56b753d6826e215db5e95bbf17695e5393dda729cef21a9fdb
          # Pas de command/args -> on reprend l’ENTRYPOINT de l’image (comme canary)
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: SETTINGS_VERBOSE
              value: "1"
            - name: MEMORY_ENABLED
              value: "true"
            - name: EMBED_MODEL_NAME
              value: "all-MiniLM-L6-v2"
            - name: EMERGENCE_VECTOR_DIR
              value: "/app/.chroma"
            - name: EMERGENCE_UPLOADS_DIR
              value: "/app/data/uploads"
            - name: EMERGENCE_DB_PATH
              value: "/app/data/emergence.db"

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: OPENAI_API_KEY
                  key: "latest"
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_API_KEY
                  key: "latest"
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ANTHROPIC_API_KEY
                  key: "latest"

            # Secrets Google OAuth / Gemini vus dans ton dump
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_OAUTH_CLIENT_SECRET
                  key: "latest"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GEMINI_API_KEY
                  key: "1"
