# Prometheus configuration for Emergence V8

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'emergence-v8'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Emergence Backend API
  - job_name: 'emergence-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Docker on Windows/Mac
        labels:
          service: 'emergence-api'
          component: 'backend'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          component: 'monitoring'

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
          component: 'monitoring'
    metrics_path: '/metrics'

  # Optional: Node exporter for system metrics
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
  #         component: 'monitoring'
