name: Deploy to Cloud Run

# Déploiement MANUEL uniquement (évite les deploys automatiques à chaque push)
# Pour déployer:
#   1. Via GitHub UI: Actions → Deploy to Cloud Run → Run workflow
#   2. Via CLI: gh workflow run deploy.yml
#   3. Via script local: pwsh -File scripts/deploy-manual.ps1
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Raison du déploiement (optionnel)'
        required: false
        type: string

env:
  GCP_PROJECT_ID: emergence-469005
  GCP_REGION: europe-west1
  SERVICE_NAME: emergence-app
  IMAGE_NAME: gcr.io/emergence-469005/emergence-app

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Configure Docker to use gcloud as credential helper for GCR
      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      # Push to Google Container Registry
      - name: Push to GCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      # Deploy to Cloud Run using stable-service.yaml to preserve auth config
      - name: Deploy to Cloud Run
        run: |
          # Update the image in stable-service.yaml
          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}:${{ github.sha }}|g" stable-service.yaml

          # Deploy using the YAML config (preserves allowlist & all env vars)
          gcloud run services replace stable-service.yaml \
            --region ${{ env.GCP_REGION }} \
            --quiet

          echo "✅ Deployed with stable-service.yaml (auth config preserved)"

      # Configure IAM Policy (ensure proper access control)
      - name: Configure IAM Policy
        run: |
          echo "🔐 Configuring IAM policy..."

          # Ensure allUsers has access (backend handles auth via allowlist)
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region ${{ env.GCP_REGION }} \
            --quiet || echo "ℹ️  allUsers already in IAM policy"

          # Remove allAuthenticatedUsers if present (too permissive, bypasses backend allowlist)
          gcloud run services remove-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --member="allAuthenticatedUsers" \
            --role="roles/run.invoker" \
            --region ${{ env.GCP_REGION }} \
            --quiet || echo "ℹ️  allAuthenticatedUsers was not in IAM policy"

          echo "✅ IAM policy configured - backend auth (allowlist) enforced"

      # Get service URL
      - name: Get Service URL
        id: service-url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.GCP_REGION }} \
            --format 'value(status.url)')
          echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "✅ Deployed to: $SERVICE_URL"

      # Verify auth configuration
      - name: Verify Auth Config
        run: |
          echo "🔐 Verifying IAM policy configuration..."
          IAM_POLICY=$(gcloud run services get-iam-policy ${{ env.SERVICE_NAME }} \
            --region ${{ env.GCP_REGION }} \
            --format json)

          # Check that allUsers IS in the bindings (backend handles auth)
          if ! echo "$IAM_POLICY" | grep -q "allUsers"; then
            echo "❌ ERROR: allUsers not found in IAM policy"
            echo "Service won't be accessible publicly (backend auth won't work)"
            exit 1
          fi

          # Check that allAuthenticatedUsers is NOT in the bindings (would bypass allowlist)
          if echo "$IAM_POLICY" | grep -q "allAuthenticatedUsers"; then
            echo "❌ ERROR: allAuthenticatedUsers found in IAM policy"
            echo "This bypasses backend allowlist - anyone with a Google account can access"
            exit 1
          fi

          echo "✅ IAM policy OK: allUsers present (backend auth), allAuthenticatedUsers absent"

      # Health check
      - name: Health Check
        run: |
          sleep 10  # Wait for service to be ready
          curl -f ${{ steps.service-url.outputs.url }}/health || exit 1
          echo "✅ Health check passed"
